# Generated by Django 5.1.1 on 2024-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_homepage_first_slide_text_homepage_second_slide_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='third_slide_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='third_slide_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='first_slide_title',
            field=models.CharField(default='Заголовок первого слайда', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_slide_title',
            field=models.CharField(default='Заголовок второго слайда', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_slide_text',
            field=models.TextField(default='Текст для первого слайда'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='second_slide_text',
            field=models.TextField(default='Текст для второго слайда'),
        ),
    ]
