# Generated by Django 5.1.1 on 2024-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_homepage_third_slide_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_slide_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_slide_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='second_slide_title',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_slide_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='first_slide_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
